package tds

import (
	"context"
	"crypto/rand"
	"encoding/binary"
	"sync/atomic"
	"time"
)

// IsolationLevel represents SQL Server transaction isolation levels.
type IsolationLevel uint8

const (
	IsolationReadUncommitted IsolationLevel = 1
	IsolationReadCommitted   IsolationLevel = 2
	IsolationRepeatableRead  IsolationLevel = 3
	IsolationSerializable    IsolationLevel = 4
	IsolationSnapshot        IsolationLevel = 5
)

func (i IsolationLevel) String() string {
	switch i {
	case IsolationReadUncommitted:
		return "READ UNCOMMITTED"
	case IsolationReadCommitted:
		return "READ COMMITTED"
	case IsolationRepeatableRead:
		return "REPEATABLE READ"
	case IsolationSerializable:
		return "SERIALIZABLE"
	case IsolationSnapshot:
		return "SNAPSHOT"
	default:
		return "UNKNOWN"
	}
}

// TransactionDescriptor is an 8-byte opaque identifier for a transaction.
// It's generated by the server and included in ALL_HEADERS by the client
// for subsequent requests within the transaction.
type TransactionDescriptor [8]byte

// transaction descriptor sequence counter
var txnSeq uint32

// NewTransactionDescriptor creates a new transaction descriptor.
// Format: 4 bytes sequence number + 4 bytes random/timestamp.
func NewTransactionDescriptor() TransactionDescriptor {
	var desc TransactionDescriptor
	seq := atomic.AddUint32(&txnSeq, 1)
	binary.LittleEndian.PutUint32(desc[0:4], seq)
	
	// Add randomness/timestamp for uniqueness across restarts
	var randBytes [4]byte
	rand.Read(randBytes[:])
	copy(desc[4:8], randBytes[:])
	
	return desc
}

// IsZero returns true if the descriptor is all zeros (no transaction).
func (d TransactionDescriptor) IsZero() bool {
	return d == TransactionDescriptor{}
}

// Bytes returns the descriptor as a byte slice.
func (d TransactionDescriptor) Bytes() []byte {
	return d[:]
}

// TransactionState tracks the state of a transaction.
type TransactionState struct {
	Descriptor     TransactionDescriptor
	Name           string
	IsolationLevel IsolationLevel
	StartedAt      time.Time
	SavepointCount int
	NestingLevel   int // For nested BEGIN TRAN
}

// TransactionManager is implemented by the application to handle
// transaction lifecycle. The TDS layer calls these hooks.
type TransactionManager interface {
	// BeginTransaction starts a new transaction and returns a descriptor.
	BeginTransaction(ctx context.Context, name string, isolation IsolationLevel) (TransactionDescriptor, error)

	// CommitTransaction commits the transaction.
	CommitTransaction(ctx context.Context, descriptor TransactionDescriptor) error

	// RollbackTransaction rolls back the transaction.
	// If savepointName is non-empty, rolls back to that savepoint.
	RollbackTransaction(ctx context.Context, descriptor TransactionDescriptor, savepointName string) error

	// CreateSavepoint creates a savepoint within the current transaction.
	CreateSavepoint(ctx context.Context, descriptor TransactionDescriptor, name string) error
}

// TransactionRequest represents a parsed transaction command.
type TransactionRequest struct {
	Type           TransactionRequestType
	Name           string         // Transaction name (for BEGIN/COMMIT)
	SavepointName  string         // Savepoint name (for SAVE/ROLLBACK TO)
	IsolationLevel IsolationLevel // For SET TRANSACTION ISOLATION LEVEL
}

// TransactionRequestType identifies the transaction operation.
type TransactionRequestType int

const (
	TxnBegin TransactionRequestType = iota
	TxnCommit
	TxnRollback
	TxnSavepoint
	TxnRollbackToSavepoint
)

func (t TransactionRequestType) String() string {
	switch t {
	case TxnBegin:
		return "BEGIN"
	case TxnCommit:
		return "COMMIT"
	case TxnRollback:
		return "ROLLBACK"
	case TxnSavepoint:
		return "SAVEPOINT"
	case TxnRollbackToSavepoint:
		return "ROLLBACK TO SAVEPOINT"
	default:
		return "UNKNOWN"
	}
}

// WriteEnvChangeBeginTran writes an ENVCHANGE token for transaction begin.
func (w *TokenWriter) WriteEnvChangeBeginTran(newDesc TransactionDescriptor, oldDesc TransactionDescriptor) {
	// ENVCHANGE format for transaction:
	// Type (1 byte) = EnvBeginTran (8)
	// NewValue length (1 byte) = 8
	// NewValue (8 bytes) = new descriptor
	// OldValue length (1 byte) = 8 or 0
	// OldValue (8 bytes) = old descriptor (or empty)

	oldLen := byte(0)
	if !oldDesc.IsZero() {
		oldLen = 8
	}

	tokenLen := 1 + 1 + 8 + 1 + int(oldLen)

	w.buf.WriteByte(byte(TokenEnvChange))
	binary.Write(&w.buf, binary.LittleEndian, uint16(tokenLen))
	w.buf.WriteByte(EnvBeginTran)
	w.buf.WriteByte(8) // new value length
	w.buf.Write(newDesc[:])
	w.buf.WriteByte(oldLen)
	if oldLen > 0 {
		w.buf.Write(oldDesc[:])
	}
}

// WriteEnvChangeCommitTran writes an ENVCHANGE token for transaction commit.
func (w *TokenWriter) WriteEnvChangeCommitTran(oldDesc TransactionDescriptor) {
	// On commit, new descriptor is empty (no active transaction)
	tokenLen := 1 + 1 + 0 + 1 + 8

	w.buf.WriteByte(byte(TokenEnvChange))
	binary.Write(&w.buf, binary.LittleEndian, uint16(tokenLen))
	w.buf.WriteByte(EnvCommitTran)
	w.buf.WriteByte(0) // new value length (no transaction)
	w.buf.WriteByte(8) // old value length
	w.buf.Write(oldDesc[:])
}

// WriteEnvChangeRollbackTran writes an ENVCHANGE token for transaction rollback.
func (w *TokenWriter) WriteEnvChangeRollbackTran(oldDesc TransactionDescriptor) {
	// On rollback, new descriptor is empty (no active transaction)
	tokenLen := 1 + 1 + 0 + 1 + 8

	w.buf.WriteByte(byte(TokenEnvChange))
	binary.Write(&w.buf, binary.LittleEndian, uint16(tokenLen))
	w.buf.WriteByte(EnvRollbackTran)
	w.buf.WriteByte(0) // new value length (no transaction)
	w.buf.WriteByte(8) // old value length
	w.buf.Write(oldDesc[:])
}

// NullTransactionManager is a stub that rejects all transaction operations.
type NullTransactionManager struct{}

func (NullTransactionManager) BeginTransaction(ctx context.Context, name string, isolation IsolationLevel) (TransactionDescriptor, error) {
	return TransactionDescriptor{}, ErrNotImplemented("transactions")
}

func (NullTransactionManager) CommitTransaction(ctx context.Context, descriptor TransactionDescriptor) error {
	return ErrNotImplemented("transactions")
}

func (NullTransactionManager) RollbackTransaction(ctx context.Context, descriptor TransactionDescriptor, savepointName string) error {
	return ErrNotImplemented("transactions")
}

func (NullTransactionManager) CreateSavepoint(ctx context.Context, descriptor TransactionDescriptor, name string) error {
	return ErrNotImplemented("transactions")
}

// ErrNotImplemented returns a standard "not implemented" error.
func ErrNotImplemented(feature string) error {
	return &NotImplementedError{Feature: feature}
}

// NotImplementedError indicates a feature is not yet implemented.
type NotImplementedError struct {
	Feature string
}

func (e *NotImplementedError) Error() string {
	return "feature not implemented: " + e.Feature
}
